#!/bin/bash

readonly work_dir="examples"
readonly dir_names=("single-cpu" "multi-gpu" "single-gpu" "multi-gpu")

for dir_name in "${dir_names[@]}"; do
    cd "${work_dir}/${dir_name}" || exit 1
    sbatch run.slurm
done
